[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.envs.default]
dependencies = [
    "conan2>=2.0.0",
    "lxml>=4.9.0",
]

[tool.hatch.envs.default.scripts]
xsd-docs = "python tools/generate_xsd_docs.py etc/ircd.xsd -o doc/xsd_documentation.md" 