name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        compiler: [gcc, clang]
        exclude:
          - os: macos-latest
            compiler: gcc

    env:
      CC: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update
          sudo apt-get install -y libjansson-dev
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install jansson
        fi
    - name: configure
      run: ./configure --enable-warnings
    - name: make
      run: make -j$( (nproc || sysctl -n hw.logicalcpu || echo 1) 2>/dev/null)
    - name: make install
      run: sudo make install
